### PR TITLE
Linux: Differentiate yara/yara-x in vmayarascan

### LINKED ISSUE #1367: Linux: vmayarascan --yara-string is broken
**Describe the bug**
`linux.vmayarascan --yara-string` crashes

**Context**
Volatility Version:  2.12.0
Operating System:  Linux
Python Version:  3.8.20
Suspected Operating System:  Linux
Command:  ```$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"```

**To Reproduce**

1. Use command:
```$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"```
3. See error
```python
$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"
Volatility 3 Framework 2.12.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value
Traceback (most recent call last):
  File "./vol.py", line 11, in <module>
    volatility3.cli.main()
  File "/home/gmoreira/vol3/volatility3/cli/__init__.py", line 917, in main
    CommandLine().run()
  File "/home/gmoreira/vol3/volatility3/cli/__init__.py", line 505, in run
    renderer.render(grid)
  File "/home/gmoreira/vol3/volatility3/cli/text_renderer.py", line 230, in render
    grid.populate(visitor, outfd)
  File "/home/gmoreira/vol3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/home/gmoreira/vol3/volatility3/framework/plugins/linux/vmayarascan.py", line 70, in _generator
    for match in rules.match(
AttributeError: 'builtins.Rules' object has no attribute 'match'
```
**Expected behavior**
```python
$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"
Volatility 3 Framework 2.9.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value

0x7f489741c001  1       default.r1      $a      45 4c 46
0x7f4897620001  1       default.r1      $a      45 4c 46
0x7f48979ab001  1       default.r1      $a      45 4c 46
0x7f4897e0b001  1       default.r1      $a      45 4c 46
0x7f4897e108f4  1       default.r1      $a      45 4c 46
0x7f4897e24151  1       default.r1      $a      45 4c 46
0x7f4897e24161  1       default.r1      $a      45 4c 46
0x7f4897e24583  1       default.r1      $a      45 4c 46
0x7f4897e250e4  1       default.r1      $a      45 4c 46
0x7f4897e25109  1       default.r1      $a      45 4c 46
0x7f4897e25114  1       default.r1      $a      45 4c 46
0x7f4897e25243  1       default.r1      $a      45 4c 46
0x7f4897e2524e  1       default.r1      $a      45 4c 46
0x7fff14da9001  1       default.r1      $a      45 4c 46
```

**Example output**
see above

**Additional information**

A git bisect identified that the issue was introduced by commit d4585be7cf4b6fbce85a6fa7a5b448b604036f86, which was integrated in PR https://github.com/volatilityfoundation/volatility3/pull/1198

### PR DESCRIPTION
**Pull request by ikelos**
Adds in code to compensate for the differences in yara and yara-x...  5:\  Really wish there were a generic interface between the two, we can't have plugins needing to know about specific implementations of yara, but I'll file a separate bug for that.  We could *probably* just force the specific scanners to have larger blocks, but failing that I'll write a shim that'll take in either yara and create a consistent interface...

I don't get the expected output (I get no results), but I don't get the exceptions any more either.

Fixes #1367

### CODE REVIEW

**Comment by ikelos** [comment]
Superceded by #1371.
