### PR TITLE
Fix up vmayarascan and vadyarascan to use yarascan properly

### LINKED ISSUE #1367: Linux: vmayarascan --yara-string is broken
**Describe the bug**
`linux.vmayarascan --yara-string` crashes

**Context**
Volatility Version:  2.12.0
Operating System:  Linux
Python Version:  3.8.20
Suspected Operating System:  Linux
Command:  ```$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"```

**To Reproduce**

1. Use command:
```$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"```
3. See error
```python
$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"
Volatility 3 Framework 2.12.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value
Traceback (most recent call last):
  File "./vol.py", line 11, in <module>
    volatility3.cli.main()
  File "/home/gmoreira/vol3/volatility3/cli/__init__.py", line 917, in main
    CommandLine().run()
  File "/home/gmoreira/vol3/volatility3/cli/__init__.py", line 505, in run
    renderer.render(grid)
  File "/home/gmoreira/vol3/volatility3/cli/text_renderer.py", line 230, in render
    grid.populate(visitor, outfd)
  File "/home/gmoreira/vol3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/home/gmoreira/vol3/volatility3/framework/plugins/linux/vmayarascan.py", line 70, in _generator
    for match in rules.match(
AttributeError: 'builtins.Rules' object has no attribute 'match'
```
**Expected behavior**
```python
$ ./vol.py -f../linux-sample-1.bin linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "ELF"
Volatility 3 Framework 2.9.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value

0x7f489741c001  1       default.r1      $a      45 4c 46
0x7f4897620001  1       default.r1      $a      45 4c 46
0x7f48979ab001  1       default.r1      $a      45 4c 46
0x7f4897e0b001  1       default.r1      $a      45 4c 46
0x7f4897e108f4  1       default.r1      $a      45 4c 46
0x7f4897e24151  1       default.r1      $a      45 4c 46
0x7f4897e24161  1       default.r1      $a      45 4c 46
0x7f4897e24583  1       default.r1      $a      45 4c 46
0x7f4897e250e4  1       default.r1      $a      45 4c 46
0x7f4897e25109  1       default.r1      $a      45 4c 46
0x7f4897e25114  1       default.r1      $a      45 4c 46
0x7f4897e25243  1       default.r1      $a      45 4c 46
0x7f4897e2524e  1       default.r1      $a      45 4c 46
0x7fff14da9001  1       default.r1      $a      45 4c 46
```

**Example output**
see above

**Additional information**

A git bisect identified that the issue was introduced by commit d4585be7cf4b6fbce85a6fa7a5b448b604036f86, which was integrated in PR https://github.com/volatilityfoundation/volatility3/pull/1198

### PR DESCRIPTION
**Pull request by ikelos**
This gets vmayarascan and vadyarascan to use the scanning framework properly, but hands in chunks that are the size of the complete vad.

This resolves issues around plugins needing to know about the version of vad whilst keeping the fix that led to the divergence...

Supercedes #1370.
Closes #1367

### CODE REVIEW

**Comment by ikelos** [comment]
This also fixes issues with the previous commit where windows code from vadyarascan made its way into vmayarascan, suggesting the review process isn't all that thorough...

File: volatility3/framework/plugins/linux/vmayarascan.py [hunk 1]
```diff
@@ -66,29 +71,36 @@ def _generator(self):
...
+                [size for (start, size) in vma_maps if size <= sanity_check]
+            )
+            scanner = yarascan.YaraScanner(rules=rules)
+            scanner.chunk_size = max_vma_size
+
+            # scan the process layer with the yarascanner
+            for offset, rule_name, name, value in proc_layer.scan(
+                context=self.context,
+                scanner=scanner,
+                sections=vma_maps,
```
Comment (gcmoreira) [inline volatility3/framework/plugins/linux/vmayarascan.py]: Your implementation includes a sanity check that filters based on `sanity_check` size, with a log message indicating those VMAs won't be scanned. However, it seems to be processing the entire `vma_maps` list regardless.. bug or I'm missing something here?

File: volatility3/framework/plugins/windows/vadyarascan.py [hunk 2]
```diff
@@ -66,49 +69,33 @@ def _generator(self):
...
+            vad_maps = list(self.get_vad_maps(task))
+            insane_vad_maps = [
+                start for (start, size) in vad_maps if size > sanity_check
+            ]
+            for start in insane_vad_maps:
+                vollog.debug(f"VAD at 0x{start:x} over sanity-check size, not scanning")
+
+            max_vad_size: int = max(
+                [size for (start, size) in vad_maps if size <= sanity_check]
+            )
```
Comment (gcmoreira) [inline volatility3/framework/plugins/windows/vadyarascan.py]: same as linux/vmayarascan.py

File: volatility3/framework/plugins/linux/vmayarascan.py [hunk 3]
```diff
@@ -66,29 +71,36 @@ def _generator(self):
...
+            for start in insane_vma_maps:
+                vollog.debug(f"VMA at 0x{start:x} over sanity-check size, not scanning")
+
+            if not vma_maps:
+                vollog.warning(f"No VMAs were found for task {task.pid}, aborting")
+                continue
+
+            max_vma_size: int = max(
+                [size for (start, size) in vma_maps if size <= sanity_check]
+            )
```
Comment (gcmoreira) [inline volatility3/framework/plugins/linux/vmayarascan.py]: There are a couple of issues with this implementation:

- Whole VMA List Used for Scanning: The scan operation ends up using the entire list. Please refer to the comment on the proc_layer.scan() call below for more details.

- Incorrect Max VMA Size Calculation: The `max_vma_size` calculation includes oversized VMAs that should be ignored.

Also, there are 4 "for" statements or loops over the same group of data and 3 list being instantiated in this small piece of code. I would recommend refactoring this to loop over the data just once. For example, you could try something like this (make sure to test it):
```python
max_vma_size: int = 0
vma_maps = []
for vma_map in self.get_vma_maps(task):
    start, size = vma_map
    if size > sanity_check:
        vollog.debug(f"VMA at 0x{start:x} over sanity-check size, not scanning")
        continue 
    elif size > max_vma_size:
        max_vma_size = size

    vma_maps.append(vma_map)

if not vma_maps:
    vollog.warning(f"No VMAs were found for task {task.pid}, aborting")
    continue
```

File: volatility3/framework/plugins/windows/vadyarascan.py [hunk 4]
```diff
@@ -66,49 +69,33 @@ def _generator(self):
...
+            scanner = yarascan.YaraScanner(rules=rules)
+            scanner.chunk_size = max_vad_size
+
+            # scan the process layer with the yarascanner
+            for offset, rule_name, name, value in layer.scan(
+                context=self.context,
+                scanner=scanner,
+                sections=vad_maps,
```
Comment (gcmoreira) [inline volatility3/framework/plugins/windows/vadyarascan.py]: same bug as plugins/linux/vmayarascan.py?

**Review by gcmoreira — CHANGES_REQUESTED** [review]

**Comment by gcmoreira** [comment]
Thanks GitHub for shuffling the order of the comments in the review :(. 
 @ikelos the first one should be this https://github.com/volatilityfoundation/volatility3/pull/1371#discussion_r1862963636 .. please let me know if anything doesn't make sense.

File: volatility3/framework/plugins/linux/vmayarascan.py (hunk 1 above)
Comment (ikelos) [reply volatility3/framework/plugins/linux/vmayarascan.py]: Ah, good catch, I did indeed mean to pass in the filtered list.

File: volatility3/framework/plugins/linux/vmayarascan.py (hunk 3 above)
Comment (ikelos) [reply volatility3/framework/plugins/linux/vmayarascan.py]: I think I was mid-refactoring it to use either the `insane_vma_size` or `max_vma_size`, but I think I got distracted.  Thanks for catching it in review!  I'll get some changes in place...

**Comment by ikelos** [comment]
Ok, lemme know if that's better...  5:)

**Comment by eve-mem** [comment]
I've tested this and it seems to fix the issue in https://github.com/volatilityfoundation/volatility3/issues/1367

```bash
(volatility3) eve@xps:~/Documents/volatility3$ ./vol.py -f linux-sample-1.dmp linux.vmayarascan.VmaYaraScan --pid 1 --yara-string "
ELF"
Volatility 3 Framework 2.12.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value

0x7f489741c001  1       r1      $a      45 4c 46
0x7f4897620001  1       r1      $a      45 4c 46
0x7f48979ab001  1       r1      $a      45 4c 46
0x7f4897e0b001  1       r1      $a      45 4c 46
0x7f4897e108f4  1       r1      $a      45 4c 46
0x7f4897e24151  1       r1      $a      45 4c 46
0x7f4897e24161  1       r1      $a      45 4c 46
0x7f4897e24583  1       r1      $a      45 4c 46
<snip>
```
I confirmed those results in volshell - and it all appears to be in order.:

```
(volatility3) eve@xps:~/Documents/volatility3$ ./volshell.py -f linux-sample-1.dmp -l
Volshell (Volatility 3 Framework) 2.12.0
Readline imported successfully  Stacking attempts finished                 

    Call help() to see available functions

    Volshell mode        : Linux
    Current Layer        : layer_name
    Current Symbol Table : symbol_table_name1
    Current Kernel Name  : kernel

(layer_name) >>> ct(1)
(layer_name_Process1) >>> db(0x7f489741c001, 8)
0x7f489741c001    45 4c 46 02 01 01 00 00                            ELF.....
(layer_name_Process1) >>> rx(b'ELF', 8)
0x7f489741c001    45 4c 46 02 01 01 00 00                            ELF.....

0x7f4897620001    45 4c 46 02 01 01 00 00                            ELF.....

0x7f48979ab001    45 4c 46 02 01 01 00 00                            ELF.....

0x7f4897e0b001    45 4c 46 02 01 01 00 00                            ELF.....

0x7f4897e108f4    45 4c 46 0f 85 6e 02 00                            ELF..n..

0x7f4897e24151    45 4c 46 02 01 01 00 00                            ELF.....

0x7f4897e24161    45 4c 46 02 01 01 03 00                            ELF.....

0x7f4897e24583    45 4c 46 3a 20 20 20 20                            ELF:....

0x7f4897e250e4    45 4c 46 20 66 69 6c 65                            ELF.file

0x7f4897e25109    45 4c 46 20 68 65 61 64                            ELF.head

0x7f4897e25114    45 4c 46 20 66 69 6c 65                            ELF.file
```


I've also tested it an actual fules file:
```bash
(volatility3) eve@xps:~/Documents/volatility3$ ./vol.py -f linux-sample-1.dmp linux.vmayarascan.VmaYaraScan --yara-file ./rules.yar
Volatility 3 Framework 2.12.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value

0x7fc90a315751  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a315766  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a31577e  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a315793  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a3157ac  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a3157c8  322     RegExpExample2  $re2    62 61 72 72
0x7fc90a3157e7  322     RegExpExample2  $re2    62 61 72 72
<snip>
```

Then on windows too

yara-string:
```
(volatility3) eve@xps:~/Documents/volatility3$ ./vol.py -f win-xp-laptop-2005-06-25.img windows.vadyarascan --yara-string "MZ"
Volatility 3 Framework 2.12.0
Progress:  100.00               PDB scanning finished                        
Offset  PID     Rule    Component       Value

0x7c900000      4       r1      $a      4d 5a
0x48580000      448     r1      $a      4d 5a
0x4858aadf      448     r1      $a      4d 5a
0x7c900000      448     r1      $a      4d 5a
0x7c910809      448     r1      $a      4d 5a
0x7c9201ff      448     r1      $a      4d 5a
0xf19a0 504     r1      $a      4d 5a
0x450000        504     r1      $a      4d 5a
0x757aaf        504     r1      $a      4d 5a
```
yara-file:
```
(volatility3) eve@xps:~/Documents/volatility3$ ./vol.py -f win-xp-laptop-2005-06-25.img windows.vadyarascan --yara-file ./rules.yar
Volatility 3 Framework 2.12.0
Progress:  100.00               PDB scanning finished                        
Offset  PID     Rule    Component       Value

0x18bfc7        504     RegExpExample2  $re2    62 61 72 57
0x18c034        504     RegExpExample2  $re2    62 61 72 33
0x18c109        504     RegExpExample2  $re2    62 61 72 33
0x81205c        504     RegExpExample2  $re2    62 61 72 33
0x86905d        504     RegExpExample2  $re2    62 61 72 33
0x869d24        504     RegExpExample2  $re2    62 61 72 57
0x869ee5        504     RegExpExample2  $re2    62 61 72 33
0x8a6174        504     RegExpExample2  $re2    62 61 72 57
0x8a62cd        504     RegExpExample2  $re2    62 61 72 33
0x8a8274        504     RegExpExample2  $re2    62 61 72 33
0x8a8d54        504     RegExpExample2  $re2    62 61 72 57
<snip>
```

For reference rules.yar:
```
rule RegExpExample2
{
    strings:
        $re1 = /foo/i    // This regexp is case-insentitive
        $re2 = /bar./s   // In this regexp the dot matches everything, including new-line
        $re3 = /baz./is  // Both modifiers can be used together
    condition:
        any of them
}
```

**Comment by ikelos** [comment]
Thanks @eve-mem , so does that still solve the problem that the original vadyarascan/vmayarascan changes were made to resolve?

**Comment by eve-mem** [comment]
e.g. a yara signature that needs the context of the entire VMA to produce a hit?

I haven't yet tested that actually....!

**Comment by ikelos** [comment]
Ok, I just know we changed it by request because the scanning worked on blocks that were too small for context (ie, the rule needed to act across the whole vad, rather than just 16Mb chunks of it).  I want to make sure we're not swapping one bug for another...  5;P

**Comment by eve-mem** [comment]
That sounds sensible - I'm just running some tests on that now.

**Comment by eve-mem** [comment]
No it doesn't seem to be working.  I created a rule that should hit a specific vma. Using some strings at the start and the end of it. 

Although I'm not sure 'all of them' conditions worked before? I have to head out for a while - I can do more testing later. 

Extracting the VMAs and running yara on it manually produces a result as expected, but trying to use the vmayarascan plugin it doesn't seem to work. :(

Here's the full testing if you wanted to recreate it:

```
# run proc maps to extract vmas
(volatility3) eve@xps:~/Documents/volatility3$ python vol.py -f linux-sample-1.dmp linux.proc.Maps --pid 8600 --dump

# use strings and head to to find something unique at the start of the vma.
(volatility3) eve@xps:~/Documents/volatility3$ strings pid.8600.vma.0x7fe78a85f000-0x7fe78a86a000.dmp | head -n 25
&F[9
'0!^a
"[1=/Z
__gmon_start__
__cxa_finalize
_Jv_RegisterClasses
rewind
fopen
__errno_location
fgets_unlocked
__ctype_b_loc
_nss_files_parse_grent
_nss_files_getgrgid_r
__pthread_mutex_lock
__pthread_mutex_unlock
fclose
_nss_files_endgrent
_nss_files_getgrnam_r
strcmp
_nss_files_setgrent
fgetpos
_nss_files_getgrent_r
fsetpos
_nss_files_parse_pwent
_nss_files_getpwuid_r

# use strings and tail to find something unique at the end of the vma.
(volatility3) eve@xps:~/Documents/volatility3$ strings pid.8600.vma.0x7fe78a85f000-0x7fe78a86a000.dmp | tail -n 25
/etc/gshadow
/etc/protocols
/etc/services
/etc/hosts
nss_files/files-hosts.c
buflen >= bufferend - buffer
bufferend <= buffer + buflen
result.h_addr_list[1] == ((void *)0)
(_res_hconf.flags & (1 << 4)) != 0
(bufferend - (char *) 0) % sizeof (char *) == 0
(((uintptr_t) newp) & (__alignof__ (struct hostent_data) - 1)) == 0
(((uintptr_t) tmp_buffer) & (__alignof__ (struct hostent_data) - 1)) == 0
_nss_files_gethostbyname4_r
_nss_files_gethostbyname2_r
_nss_files_gethostbyname_r
/etc/networks
/etc/rpc
/etc/ethers
/etc/netgroup
/etc/publickey
#       :
/etc/aliases
:include:
/lib64/ld-linux-x86-64.so.2
;*3$"

# move the extracted vmas to a folder to make scanning easier
(volatility3) eve@xps:~/Documents/volatility3$ mkdir maps
(volatility3) eve@xps:~/Documents/volatility3$ mv pid*dmp maps/

# use the normal 'yara' tool against the extracted files, note the hit on `pid.8600.vma.0x7fe78a85f000-0x7fe78a86a000.dmp`
(volatility3) eve@xps:~/Documents/volatility3$ yara fullvma.yar maps/
fullvmayarascan maps//pid.8600.vma.0x7fe78a85f000-0x7fe78a86a000.dmp

# attempt the same scan with linux.vmayarascan.VmaYaraScan - no hits... :(
(volatility3) eve@xps:~/Documents/volatility3$ ./vol.py -f linux-sample-1.dmp linux.vmayarascan.VmaYaraScan --yara-file ./fullvma.yar 
Volatility 3 Framework 2.12.0
Progress:  100.00               Stacking attempts finished                 
Offset  PID     Rule    Component       Value
```

Here is the rule I used for testing:
```
rule fullvmayarascan
{
    strings:
        $s1 = "_nss_files_parse_grent"
        $s2 = "/lib64/ld-linux-x86-64.so.2"
        $s3 = "(bufferend - (char *) 0) % sizeof (char *) == 0"
    condition:
        all of them
}
```

**Comment by ikelos** [comment]
Ok, yep, seems it's still getting cut into 4096 byte blocks to be scanned.  I think I'll need to make a BufferedScanner that can rechunk things.  I've fixed up #1370 at least to work properly with both (previously it had a mistake of thinking the response was `start, end` rather than `start, size` as well as a number of issues with the yara_x return values in particular...

**Comment by eve-mem** [comment]
Glad you reminded me to even check... 

Let me know if there's anything else i can help with on this one.

**Comment by gcmoreira** [comment]
Great job! It turns out there was more to address.

I've created a Linux test case for the latest bug using the steps provided by @eve-mem above. Feel free to incorporate it (or a similar version) into this PR. You may also want to include more detailed output validation.
We should also add the Windows counterpart.

```diff
diff --git a/test/test_volatility.py b/test/test_volatility.py
index 847be88d9..e94761499 100644
--- a/test/test_volatility.py
+++ b/test/test_volatility.py
@@ -14,6 +14,7 @@ import tempfile
 import hashlib
 import ntpath
 import json
+import contextlib
 
 #
 # HELPER FUNCTIONS
@@ -379,6 +381,42 @@ def test_linux_library_list(image, volatility, python):
     assert rc == 0
 
 
+def test_linux_vmayarascan_yara_rule(image, volatility, python):
+    yara_rule_01 = r"""
+        rule fullvmayarascan
+        {
+            strings:
+                $s1 = "_nss_files_parse_grent"
+                $s2 = "/lib64/ld-linux-x86-64.so.2"
+                $s3 = "(bufferend - (char *) 0) % sizeof (char *) == 0"
+            condition:
+                all of them
+        }
+    """
+
+    # FIXME: When the minimum Python version includes 3.12, replace the following with:
+    # with tempfile.NamedTemporaryFile(delete_on_close=False) as fd: ...
+    fd, filename = tempfile.mkstemp(suffix=".yar")
+    try:
+        with os.fdopen(fd, "w") as f:
+            f.write(yara_rule_01)
+
+        rc, out, _err = runvol_plugin(
+            "linux.vmayarascan.VmaYaraScan",
+            image,
+            volatility,
+            python,
+            pluginargs=["--pid", "8600", "--yara-file", filename],
+        )
+    finally:
+        with contextlib.suppress(FileNotFoundError):
+            os.remove(filename)
+
+    out = out.lower()
+    assert out.count(b"\n") > 4
+    assert rc == 0
+
+
```

Regarding the unit tests, I'm not sure if we should have a separate test for each plugin's functionality or combine everything into one comprehensive test case. I chose the former, but it's up to you. If we go with a combined test, we'll need to merge the above code with the test case in my other PR [here](https://github.com/volatilityfoundation/volatility3/pull/1368/files#diff-ee4e5280e1727b84afe71ba6398d57a9b3969413270e3d5587494efb175dc4ebR529).

**Comment by ikelos** [comment]
Even with a patch to scanning to chunk together on the layer it's on, it doesn't return any results because the scanner scans by contiguous blocks, meaning if there's unmapped pages in the middle, the two sections won't be joined together and vast searches won't work.

Yara also doesn't have an interface to accept a file-like object, meaning we have to read the entire VAD/VMA into memory and then scan it (no matter how big it is).  Not ideal, but about the only practical solution at the moment.

So I've used YaraScanner as effectively a common interface to the two yara implementations.  Hopefully everything works now and returns the right results?

I would like to get the testing added in (this is a great testcase!) but I don't want to keep holding this up given the need to break the cyclic dependency on registry before the test case works, so please submit that in a separate PR...

**Comment by gcmoreira** [comment]
> I don't want to keep holding this up given the need to break the cyclic dependency on registry before the test case works, so please submit that in a separate PR..

Oh sorry for the confusion, I think you are talking about my comment on the other ticket, right?  that only happens in vscode not on GitHub. And it's due to the way it discovers the test files. The vscode test plugin wants to list them on the user interface, so you can choose which one you want to execute. But for doing that, it has to import all of them. 
On GitHub we only execute the test files we want. So, the bug is not triggered.

**Comment by ikelos** [comment]
Ok, so if I add the test case into this PR it should be fine?  No problem then, I'll give it a go and we'll see.  Thanks for the speedy reply!  5:)

**Comment by eve-mem** [comment]
I can make a Windows test this evening. I'll do both the yara files and the yara strings options to cover those options and stop one of them breaking later again.

**Comment by eve-mem** [comment]
100% plagiarizing the great linux tests from @gcmoreira... but these tests here should work well for the windows sample.

I'm not sure how to properly suggest the changes for a PR to make it easier for you to merge in @ikelos ... hopefully this is easy enough. 

```python
def test_windows_vadyarascan_yara_rule(image, volatility, python):
    yara_rule_01 = r"""
        rule fullvadyarascan
        {
            strings:
                $s1 = "!This program cannot be run in DOS mode."
                $s2 = "Qw))Pw"
                $s3 = "W_wD)Pw"
                $s4 = "1Xw+2Xw"
                $s5 = "xd`wh``w"
                $s6 = "0g`w0g`w8g`w8g`w@g`w@g`wHg`wHg`wPg`wPg`wXg`wXg`w`g`w`g`whg`whg`wpg`wpg`wxg`wxg`w"
            condition:
                all of them
        }
    """

    # FIXME: When the minimum Python version includes 3.12, replace the following with:
    # with tempfile.NamedTemporaryFile(delete_on_close=False) as fd: ...
    fd, filename = tempfile.mkstemp(suffix=".yar")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(yara_rule_01)

        rc, out, _err = runvol_plugin(
            "windows.vadyarascan.VadYaraScan",
            image,
            volatility,
            python,
            pluginargs=["--pid", "4012", "--yara-file", filename],
        )
    finally:
        with contextlib.suppress(FileNotFoundError):
            os.remove(filename)

    out = out.lower()
    assert out.count(b"\n") > 4
    assert rc == 0

def test_windows_vadyarascan(image, volatility, python):
    rc, out, _err = runvol_plugin(
        "windows.vadyarascan.VadYaraScan",
        image,
        volatility,
        python,
        pluginargs=["--pid", "4012", "--yara-string", "MZ"],
    )
    out = out.lower()

    assert out.count(b"\n") > 10
    assert rc == 0
```

Here is a run of  that windows yara rule file (using the command line tool) to show it should just hit on one of the extracted areas:
```
(volatility3) eve@xps:~/Documents/volatility3$ yara fullvadyarascan.yar win/
fullvadyarascan win//pid.4012.vad.0x774e0000-0x7761cfff.dmp
```


Here is the output of the yara string option:
```
(volatility3) eve@xps:~/Documents/volatility3$ python vol.py -f win-xp-laptop-2005-06-25.img windows.vadyarascan --pid 4012  --yara
-string MZ
Volatility 3 Framework 2.12.0
Progress:  100.00               PDB scanning finished                        
Offset  PID     Rule    Component       Value

0x400000        4012    r1      $a      4d 5a
0x406bf2        4012    r1      $a      4d 5a
0x10000000      4012    r1      $a      4d 5a
0x774e0000      4012    r1      $a      4d 5a
0x774edcb5      4012    r1      $a      4d 5a
0x77c00000      4012    r1      $a      4d 5a
0x77c10000      4012    r1      $a      4d 5a
0x77c2a146      4012    r1      $a      4d 5a
0x77c393e7      4012    r1      $a      4d 5a
0x77d40000      4012    r1      $a      4d 5a
0x77dd0000      4012    r1      $a      4d 5a
0x77e70000      4012    r1      $a      4d 5a
0x77f10000      4012    r1      $a      4d 5a
0x77fe0000      4012    r1      $a      4d 5a
0x7c000000      4012    r1      $a      4d 5a
0x7c800000      4012    r1      $a      4d 5a
0x7c900000      4012    r1      $a      4d 5a
0x7c910809      4012    r1      $a      4d 5a
0x7c9201ff      4012    r1      $a      4d 5a
```

EDIT: I swapped the yara rule for something that hits in a much bigger area. If you get the email alerts it might have contained an older version of the rule.

**Comment by ikelos** [comment]
Ok, all added, I guess we'll see if it all works.  I'll ask Gus for a rereview too...  5:)

**Review by gcmoreira — APPROVED** [review]
@ikelos @eve-mem  It looks awesome. Great to see the new test cases added and the implementation successfully passing all of them. Excellent teamwork! 

A small improvement to these plugins could be to add `sanity_check` as a parameter with its default value, in case someone wants to allow larger VMAs. But this is outside the scope of the current PR and can be done in a future one.

**Comment by gcmoreira** [comment]
@ikelos great! I will merge this changes on [!1366](https://github.com/volatilityfoundation/volatility3/pull/1368) soon, so we can also proceed with that one.

@eve-mem another idea for another PR could be to use the `format_hints.HexBytes` formatter. 

## Before
```shell
$ python3 ./vol.py -r pretty \
    -f ./linux-sample-1.bin \
    linux.vmayarascan.VmaYaraScan \
    --pid 8600 \
    --yara-file fullvma.yar
Volatility 3 Framework 2.12.0
Formatting...0.00               Stacking attempts finished                 
  |         Offset |  PID |                    Rule | Component |                                                                                                                                        Value
* | 0x7fe78a8600a6 | 8600 | default.fullvmayarascan |       $s1 |                                                                            5f 6e 73 73 5f 66 69 6c 65 73 5f 70 61 72 73 65 5f 67 72 65 6e 74
* | 0x7fe78a8683f0 | 8600 | default.fullvmayarascan |       $s2 |                                                             2f 6c 69 62 36 34 2f 6c 64 2d 6c 69 6e 75 78 2d 78 38 36 2d 36 34 2e 73 6f 2e 32
* | 0x7fe78a868260 | 8600 | default.fullvmayarascan |       $s3 | 28 62 75 66 66 65 72 65 6e 64 20 2d 20 28 63 68 61 72 20 2a 29 20 30 29 20 25 20 73 69 7a 65 6f 66 20 28 63 68 61 72 20 2a 29 20 3d 3d 20 30
```

## After
```shell
$ python3 ./vol.py -r pretty \
    -f ./linux-sample-1.bin \
    linux.vmayarascan.VmaYaraScan \
    --pid 8600 \
    --yara-file fullvma.yar
Volatility 3 Framework 2.12.0
Formatting...
  |         Offset |  PID |                    Rule | Component |                                                            Value
* | 0x7fe78a8600a6 | 8600 | default.fullvmayarascan |       $s1 |                                                                 
  |                |      |                         |           | 5f 6e 73 73 5f 66 69 6c 65 73 5f 70 61 72 73 65 _nss_files_parse
  |                |      |                         |           | 5f 67 72 65 6e 74                               _grent          
* | 0x7fe78a8683f0 | 8600 | default.fullvmayarascan |       $s2 |                                                                 
  |                |      |                         |           | 2f 6c 69 62 36 34 2f 6c 64 2d 6c 69 6e 75 78 2d /lib64/ld-linux-
  |                |      |                         |           | 78 38 36 2d 36 34 2e 73 6f 2e 32                x86-64.so.2     
* | 0x7fe78a868260 | 8600 | default.fullvmayarascan |       $s3 |                                                                 
  |                |      |                         |           | 28 62 75 66 66 65 72 65 6e 64 20 2d 20 28 63 68 (bufferend - (ch
  |                |      |                         |           | 61 72 20 2a 29 20 30 29 20 25 20 73 69 7a 65 6f ar *) 0) % sizeo
  |                |      |                         |           | 66 20 28 63 68 61 72 20 2a 29 20 3d 3d 20 30    f (char *) == 0 
```
How do you feel about that? That output is after [this](https://github.com/volatilityfoundation/volatility3/pull/1376) fix.
